--floatapps =
--{
--  ["MPlayer"] = true,
--  ["gimp"] = true,
--  ["smplayer"] = true,
--  ["gnome-mplayer"] = true,
--}

--apptags =
--{
--  ["pidgin"] = { screen = 1, tag = 7 },
--  ["stardict"] = { screen = 1, tag = 5 },
--}
