os.execute ("setxkbmap -layout 'us,ru'")
os.execute ("setxkbmap -option 'grp:shift_toggle,grp_led:scroll,terminate:ctrl_alt_bksp'")
os.execute ("xrandr --setprovideroutputsource modesetting NVIDIA-0 && xrandr --auto")
--os.execute (os.getenv("HOME").."/.config/awesome/set_wall.sh "..os.getenv("HOME").."/.config/awesome/wallpaper.slink &")
os.execute ("pgrep xscreensaver || xscreensaver -no-splash &")
os.execute ("pgrep mail_loop.sh || "..os.getenv("HOME").."/.config/awesome/mail_loop.sh &")
os.execute ("pgrep nm-applet || nm-applet &")
os.execute ("numlockx on &")
--os.execute ("smbnetfs "..os.getenv("HOME").."/smb &")
--os.execute ("pgrep lightsOn.sh || "..os.getenv("HOME").."/.config/awesome/lightsOn.sh &")
--os.execute ("pgrep urxvt || urxvt &")
--os.execute ("pgrep stardict || stardict &")
--os.execute ("pgrep pidgin || pidgin &")
--os.execute ("pgrep firefox || (firefox || firefox-bin) &")
os.execute ("xrandr --output HDMI-0 --left-of eDP-1-1 --mode 1920x1080 &")
