os.execute ("numlockx on &")
os.execute ("xsetroot -cursor_name left_ptr &")
os.execute ("xscreensaver -no-splash &")
os.execute ("pidgin &")
os.execute ("pgrep stardict || stardict &")
os.execute ("pgrep urxvt || urxvt &")
os.execute ("pgrep firefox || (firefox || firefox-bin) &")
os.execute ("smbnetfs "..os.getenv("HOME").."/smb -o umask=111")
os.execute (os.getenv("HOME").."/.config/awesome/set_wall.sh "..os.getenv("HOME").."/wallpapers/")
